language: node_js

matrix:
  include:
    - node_js: "10"
      env: RUN_COVERAGE=true 

install:
  - echo "hi dave"

script:
  - rm -rf ./node_modules
  - npm install
  - npm ls
  - |
      if [ -n "$RUN_COVERAGE" ]; then
        npm run test-cov
        cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
      else
        npm run test
      fi