language: node_js


matrix:
  include:
    - node_js: "10"
    - node_js: "9"
    - node_js: "8"
    - node_js: "7"
    - node_js: "6"
      env: RUN_COVERAGE=true 

install:
  - ls ./node_modules
  - npm install
  - ls ./node_modules

script:
  - |
      if [ -n "$RUN_COVERAGE" ]; then
        npm run test-cov
        cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
      else
        npm run test
      fi