language: node_js

matrix:
  include:
    - node_js: "10"
      env: RUN_COVERAGE=true 

before_install:
  # Upgrade NPM, see if that makes npm install more relaiable?
  - npm i -g npm

install:
  - echo "hi dave"

script:
  - npm install
  - npm ls
  # Run test, optionally with coverage enabled.  Return non-0 if tests fail
  - |
      if [ -n "$RUN_COVERAGE" ]; then
        if npm run test-cov; then
          cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
          exit 0
        fi
      else
        if npm run test; then
          exit 0
        fi
      fi
      exit 1