language: node_js

matrix:
  include:
    - node_js: "10"
      env: RUN_COVERAGE=true 

before_install:
  # Upgrade NPM, see if that makes npm install more relaiable?
  - npm i -g npm

install:
  - echo "hi dave"

script:
  - npm install
  - npm ls
  - |
      if [ -n "$RUN_COVERAGE" ]; then
        npm run test-cov
        cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
      else
        npm run test
      fi